name: demand_prediction_app
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: "^3.5.4"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/fonts/
